/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a46d655b-ac47-4022-9bc2-353becb5304f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_diWn5Hywf",
    "aws_user_pools_web_client_id": "58gtecbnl1hdekf1tk5iivkm7u",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "api0562b1e3",
            "endpoint": "https://ahuycp0ea3.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_social_provoders": [],
    "aws_cognito_mfa_configration": "OFF"
};


export default awsmobile;
